### PR TITLE
Add 'tab' option

### PR DESCRIPTION
**Pull request by loklaan**
Hi there!

One of the maintainers on [tslide/tslide][tslide] is trying to add this renderer to the project, but ran into an [issue][tslide17] with the size of tabs changing expecting behaviour. So, thought I'd throw this PR out to add an option to change the default tab fixture (which I thought was 4, but was actually 3!).

I was going to add the option to require numbers to specify the number of spaces, but then you can't use a \t char in place of spaces (possible case), so instead it can currently take any arbitrary string.

Let me know what you think of the PR, cheers!

[tslide]: https://github.com/tslide/tslide
[tslide17]: https://github.com/tslide/tslide/pull/17

### CODE REVIEW

**Comment by mikaelbr** [comment]
Hi. Thanks for this! I don't remember if the tab was set to 3 because it looked better or just laziness, but this customise step makes sense.

Are we sure the `tab` property is the most intuitive API? Should it be `useTabs` and `tabSize` instead, or do you think this is fine? Another option could be to have `tab: 4` or `tab: '\t'` but as with specifying `tabs: '   '` you can have issues where people put in what ever (unsanitized etc), but maybe this isn't a problem.

**Comment by loklaan** [comment]
Sounds good.

At the moment there is no error management in the codebase - would you want the sanitization to fall back on on the default tab option if it the user provided tab failed the check?

**Comment by mikaelbr** [comment]
I think that is just fine 👍 I can add you as a collaborator to the project if you want?

**Comment by loklaan** [comment]
Sounds great 👍 Nice one. I'll add this and merge it in.

Would you mind publishing the new version yourself, or give collab on the npm package as well?

**Comment by mikaelbr** [comment]
I can add it to NPM so you don't have to do [all the tagging and changelog-writing stuff](https://github.com/mikaelbr/marked-terminal/releases). But if you want I can add you on NPM as well.

**Comment by loklaan** [comment]
I am happy with you doing that stuff :wink:.

**Comment by mikaelbr** [comment]
Hehe, not surprised 🍰

**Comment by mikaelbr** [comment]
I'll do a minor release later today!

**Comment by loklaan** [comment]
Awesome, looking forward to it.

Thanks for being super responsive!

**Comment by mikaelbr** [comment]
All credit to you for giving proper insights into what the problem is, why it's a problem and to provide a solution. Without that I probably wouldn't have found the time to do this right now.

**Comment by mikaelbr** [comment]
```
~/Documents/Sites/repos/marked-terminal master 6s
❯ npm publish
+ marked-terminal@1.7.0
```

https://github.com/mikaelbr/marked-terminal/releases/tag/v1.7.0

**Pull request merged**
