### PR TITLE
Update to cardinal@1.0.0

### PR DESCRIPTION
**Pull request by hzoo**
https://github.com/thlorenz/cardinal/commits/master

### CODE REVIEW

**Comment by mikaelbr** [comment]
Thanks!

**Comment by hzoo** [comment]
Thanks! And for context since its kind of random, https://mobile.twitter.com/zpao/status/771502203559223297

**Comment by mikaelbr** [comment]
Ah. Didn't catch that, even if actually saw that tweet earlier today... 👎 

It'll be fixed and a new version will be out within short time! 🍰 Thanks for letting me know.

**Comment by mikaelbr** [comment]
New version out now!

**Pull request merged**
