### PR TITLE
feat: reintroduce cjs support via bundling

### LINKED ISSUE #97: Introduce hybrid cjs/esm support?
heya @mikaelbr, thanks for your library.
`marked@4.0.10` supports both cjs and esm. would you consider accepting a PR that bundles `index.js` into an additional `index.cjs`, reviving support for cjs as well?

I'm asking because I've installed `firebase-tools`, which uses this library, and got the following:
`warning "firebase-tools > marked-terminal@3.3.0" has incorrect peer dependency "marked@^0.4.0 || ^0.5.0 || ^0.6.0 || ^0.7.0".`

`firebase-tools` is cjs. they upgraded to the latest `marked@4 `(due to a security issue), but couldn't upgrade `marked-terminal`, as it's esm only.

WDYT?

### PR DESCRIPTION
**Pull request by AviVahl**
closes #97

### CODE REVIEW

**Comment by mikaelbr** [comment]
Cool. Checking out now.

**Comment by mikaelbr** [comment]
Would this require peer dependency of 4.0.2 or over?

**Comment by AviVahl** [comment]
peerDep of `marked` shouldn't change, as far as I can tell.
if anything, this made it a bit easier to use with older marked.

**Comment by AviVahl** [comment]
Oh wait, I'm pushing a tiny improvement to "exports" to match info at:
https://nodejs.org/dist/latest-v16.x/docs/api/packages.html#nested-conditions

**Comment by mikaelbr** [comment]
You're right, thinking about it more if using 4.0.0 you can still use this and then choose the ESM edition. So works as before. Tested out locally and seems to work as expected! Was looking into and verifying the exports property aswell. Good suggestion to update it! Awaiting commit

**Comment by AviVahl** [comment]
Pushed. :+1:

**Comment by mikaelbr** [comment]
Thanks! Good work 🍰

**Comment by AviVahl** [comment]
@mikaelbr I forget to add "index.cjs" to the "files" field of package.json :( just checked 5.1.0 and published package doesn't include it. my bad.

**Comment by mikaelbr** [comment]
Hah, dang it. I should have checked that. I packaged it up but was to lazy to check contents 🤦  I'll fix it

**Comment by mikaelbr** [comment]
Screenshot 2022-01-26 at 18 08 00
Screenshot 2022-01-26 at 18 08 40

**Pull request merged**
