### PR TITLE
Allow paragraph reflow and add option to remove section marks

### PR DESCRIPTION
**Pull request by rocky**
Hi - 

I'm using marked-terminal in the node debug replacement [trepanjs](https://www.npmjs.com/package/trepanjs). 

There are two features I'd like to see:

* reflow of paragraph text which normally occurs in markdown text.
* removal of section headers, e.g. `#`, `##` etc

Rather than change this unconditionally, I've added options for each feature. 

Thanks.

### CODE REVIEW

**Comment by mikaelbr** [comment]
Hi! Thanks for this. Doing something like reflow is a good idea I think.
But should this feature also go for other types of block elements, such as headers and lists?
In that case, lists might be a problem for nested elements.

**Comment by rocky** [comment]
Ok, headers have now been added the list of things to be reflowed. Also, I've corrected the reflow code so that we go right up against the margin.

(Should reflow be an option as it currently is? And if so, should the default be off as it currently is?)

As for lists, since as you observer that opens up complications, I have left that for later. What is there now, I think is an improvement; it definitely covers all of my needs in trepanjs. 

Should you want to go further, great! I'd consider dabbling with it, but only after seeing this much get out as I could use this right away.

Thanks.

**Comment by mikaelbr** [comment]
I think leaving lists out for now is good. And the default options sounds reasonable.
You should add "reflowText: false" in the default options object though.

Also, could you fix the breaking tests and squash the commits, and I'll merge?

**Comment by rocky** [comment]
Ok. All is well now.

**Comment by mikaelbr** [comment]
LGTM! Thanks.

**Pull request merged**
