### PR TITLE
Upgrade to marked 0.5.0

### PR DESCRIPTION
**Pull request by millette**

### CODE REVIEW

**Comment by mikaelbr** [comment]
Thanks! Are there any breaking changes we should know of?

**Comment by millette** [comment]
The [marked release](https://github.com/markedjs/marked/releases/tag/v0.5.0) mentions a few regarding markdown syntax. I didn't see a problem upgrading my little module.

**Comment by millette** [comment]
It probably failed on node 10 because I edited package.json directly the GitHub and didn't update the lock file.

**Comment by millette** [comment]
Thanks! Eagerly awaiting the npm release :-)

**Pull request merged**
