### PR TITLE
Add support for hyperlinks in terminal

### PR DESCRIPTION
**Pull request by horosgrisa**
Add support for hyperlinks in terminal using [terminal-link](https://www.npmjs.com/package/terminal-link)

### CODE REVIEW

**Comment by mikaelbr** [comment]
Hi! Thanks for this! 🍰 

Could you look into expanding the tests and fix them as well? I think also it using the fallback option for terminal-link would be a good idea. If links aren't supported, fallback to existing functionality

**Comment by mikaelbr** [comment]
@horosgrisa Hi! Why did you close this?

**Comment by horosgrisa** [comment]
Hello. I closed this because terminal-link isn't good library. I will create another pull-request when I rewrite code with `asci-escapes` library.

**Comment by mikaelbr** [comment]
Ok. Thanks

**Pull request closed without merging**
